permalink: /:year-:month-:day/:title/

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: [
   "no_intra_emphasis"
   ,"fenced_code_blocks"
   ,"autolink"
   ,"tables"
   ,"strikethrough"
   ,"superscript"
   ,"with_toc_data"
   ,"footnotes"
   ,"highlight"
   ,"underline"
   ,"quote"
   ,"lax_spacing"
   ,"prettify"
#   ,"html_toc"
  ]



paginate: 10
paginate_path: ":num"
baseurl: ""



title: "The 20 Year Plan"
email: "jxieeducation[at]gmail.com"
description: "Getting better"
github_username:  "jxieeducation"
disqus_shortname: "jxieeducation"


url: "http://jxieeducation.com"
imgrepo: "http://jxieeducation.com/static/img"
# url: "http://127.0.0.1:4000"
# imgrepo: "http://127.0.0.1:4000/static/img"
